# Generated by Django 6.0.3 on 2026-03-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin tiempo estimado'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '60 minutos')], default=0),
        ),
    ]
