# Generated by Django 6.0.3 on 2026-03-09 06:22

from django.db import migrations, models


def normalize_estimated_minutes(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    Task.objects.filter(estimated_minutes__in=[0, None]).update(estimated_minutes=15)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_estimated_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '60 minutos')], default=15),
        ),
        migrations.RunPython(normalize_estimated_minutes, migrations.RunPython.noop),
    ]
